//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodForFriends.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMenu
    {
        public int ID { get; set; }
        public Nullable<int> MenuID { get; set; }
        public string UserID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
